# Configuration for GitHub Actions Labeler
# https://github.com/actions/labeler

internal:
  - changed-files:
      - any-glob-to-any-file:
          - internal/**
          - internal/**/*

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**
          - .github/actions/**
          - dependency_range_tests/**
          - dependency_range_tests/**/*
          - environment_tests/**
          - environment_tests/**/*
          - libs/langchain-standard-tests/**
          - libs/langchain-standard-tests/**/*

examples:
  - changed-files:
      - any-glob-to-any-file:
          - examples/**
          - examples/**/*

pkg:langchain:
  - changed-files:
      - any-glob-to-any-file:
          - libs/langchain/**
          - libs/langchain/**/*

pkg:@langchain/classic:
  - changed-files:
      - any-glob-to-any-file:
          - libs/langchain-classic/**
          - libs/langchain-classic/**/*

pkg:@langchain/core:
  - changed-flies:
      - any-glob-to-any-file:
          - libs/langchain-core/**
          - libs/langchain-core/**/*

pkg:@langchain/mcp-adapters:
  - changed-files:
      - any-glob-to-any-file:
          - libs/langchain-mcp-adapters/**
          - libs/langchain-mcp-adapters/**/*

pkg:@langchain/textsplitters:
  - changed-files:
      - any-glob-to-any-file:
          - libs/langchain-textsplitters/**
          - libs/langchain-textsplitters/**/*

pkg:@langchain/anthropic:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-anthropic/**
          - libs/providers/langchain-anthropic/**/*

pkg:@langchain/aws:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-aws/**
          - libs/providers/langchain-aws/**/*

pkg:@langchain/cloudflare:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-cloudflare/**
          - libs/providers/langchain-cloudflare/**/*

pkg:@langchain/deepseek:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-deepseek/**
          - libs/providers/langchain-deepseek/**/*

pkg:@langchain/google-common:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-google-common/**
          - libs/providers/langchain-google-common/**/*

pkg:@langchain/google-gauth:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-google-gauth/**
          - libs/providers/langchain-google-gauth/**/*

pkg:@langchain/google-genai:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-google-genai/**
          - libs/providers/langchain-google-genai/**/*

pkg:@langchain/google-vertexai:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-google-vertexai/**
          - libs/providers/langchain-google-vertexai/**/*

pkg:@langchain/google-vertexai-web:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-google-vertexai-web/**
          - libs/providers/langchain-google-vertexai-web/**/*

pkg:@langchain/google-webauth:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-google-webauth/**
          - libs/providers/langchain-google-webauth/**/*

pkg:@langchain/groq:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-groq/**
          - libs/providers/langchain-groq/**/*

pkg:@langchain/mistralai:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-mistralai/**
          - libs/providers/langchain-mistralai/**/*

pkg:@langchain/mongodb:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-mongodb/**
          - libs/providers/langchain-mongodb/**/*

pkg:@langchain/ollama:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-ollama/**
          - libs/providers/langchain-ollama/**/*

pkg:@langchain/openai:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-openai/**
          - libs/providers/langchain-openai/**/*

pkg:@langchain/redis:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-redis/**
          - libs/providers/langchain-redis/**/*

pkg:@langchain/xai:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-xai/**
          - libs/providers/langchain-xai/**/*

pkg:@langchain/valkey:
  - changed-files:
      - any-glob-to-any-file:
          - libs/providers/langchain-valkey/**
          - libs/providers/langchain-valkey/**/*
