// Auto-generated by lc-secrets plugin. Do not edit manually.

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface OptionalImportMap {}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface SecretMap {}
