import * as fs from "node:fs";
import * as path from "node:path";
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import type { ModelProfile } from "@langchain/core/language_models/profile";
import type { Model, ProviderMap } from "./api-schema.js";
import {
  type ModelProfileOverride,
  applyOverrides,
  findMonorepoRoot,
  validatePathInMonorepo,
} from "./config.js";

function modelToProfile(model: Model): ModelProfile {
  return {
    maxInputTokens: model.limit?.context,
    imageInputs: model.modalities?.input?.includes("image") ?? false,
    audioInputs: model.modalities?.input?.includes("audio") ?? false,
    pdfInputs: model.modalities?.input?.includes("pdf") ?? false,
    videoInputs: model.modalities?.input?.includes("video") ?? false,
    maxOutputTokens: model.limit?.output,
    reasoningOutput: model.reasoning ?? false,
    imageOutputs: model.modalities?.output?.includes("image") ?? false,
    audioOutputs: model.modalities?.output?.includes("audio") ?? false,
    videoOutputs: model.modalities?.output?.includes("video") ?? false,
    toolCalling: model.tool_call ?? false,
    structuredOutput: model.structured_output ?? false,
  };
}

function toConstantName(key: string): string {
  const name = key
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toUpperCase()
    .replace(/[^A-Z0-9_]/g, "_");
  return /^\d/.test(name) ? `_${name}` : name;
}

function hoistSharedArrayConstants(models: Record<string, ModelProfile>): {
  declarations: string[];
  identifierFor: Map<string, string>;
} {
  const groups = new Map<
    string,
    { key: string; value: unknown[]; count: number }
  >();
  for (const profile of Object.values(models)) {
    for (const [key, value] of Object.entries(profile)) {
      if (!Array.isArray(value)) continue;
      const groupKey = `${key}\u0000${JSON.stringify(value)}`;
      const existing = groups.get(groupKey);
      if (existing) existing.count += 1;
      else groups.set(groupKey, { key, value, count: 1 });
    }
  }

  const usedNames = new Set<string>();
  const identifierFor = new Map<string, string>();
  const declarations: string[] = [];
  for (const [groupKey, group] of groups) {
    if (group.count < 2) continue;
    const baseName = toConstantName(group.key);
    let identifier = baseName;
    let suffix = 2;
    while (usedNames.has(identifier)) {
      identifier = `${baseName}_${suffix++}`;
    }
    usedNames.add(identifier);
    identifierFor.set(groupKey, identifier);
    declarations.push(`const ${identifier} = ${JSON.stringify(group.value)};`);
  }
  return { declarations, identifierFor };
}

function propertyName(key: string, allowIdentifier = false): string {
  const quoted = JSON.stringify(key);
  if (key === "__proto__") return `[${quoted}]`;
  return allowIdentifier && /^[a-zA-Z_$][\w$]*$/.test(key) ? key : quoted;
}

function generateTypeScript(models: Record<string, ModelProfile>): string {
  const { declarations, identifierFor } = hoistSharedArrayConstants(models);
  const modelProfiles = Object.entries(models)
    .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))
    .map(([modelName, profile]) => {
      const properties = Object.entries(profile)
        .filter(([, value]) => value !== undefined)
        .map(([key, value]) => {
          const groupKey = Array.isArray(value)
            ? `${key}\u0000${JSON.stringify(value)}`
            : undefined;
          const expression =
            (groupKey ? identifierFor.get(groupKey) : undefined) ??
            JSON.stringify(value);
          return `${propertyName(key, true)}: ${expression}`;
        });
      return `${propertyName(modelName)}: {\n${properties.join(",\n")}\n}`;
    });
  return [
    "/**\n * This file was automatically generated by an automated script. Do not edit manually.\n */",
    'import type { ModelProfile } from "@langchain/core/language_models/profile";',
    ...declarations,
    `const PROFILES: Record<string, ModelProfile> = {\n${modelProfiles.join(",\n")}\n};`,
    "export default PROFILES;\n",
  ].join("\n");
}

async function fetchProviderData(): Promise<ProviderMap> {
  const response = await fetch("https://models.dev/api.json", {
    signal: AbortSignal.timeout(30000),
  });
  if (!response.ok) {
    throw new Error(`Failed to fetch models.dev API: ${response.statusText}`);
  }
  return (await response.json()) as ProviderMap;
}

export async function generateModelProfiles(
  providerId: string,
  providerOverrides: ModelProfileOverride,
  modelOverrides: Record<string, ModelProfileOverride>,
  outputPath: string
): Promise<void> {
  console.log("Fetching provider data from models.dev API...");
  const data = await fetchProviderData();
  const provider = data[providerId];
  if (!provider) {
    throw new Error(`Provider "${providerId}" not found in models.dev API`);
  }
  if (
    !provider.models ||
    typeof provider.models !== "object" ||
    Array.isArray(provider.models) ||
    !Object.keys(provider.models).length
  ) {
    throw new Error(`Provider "${providerId}" has no valid model data`);
  }
  console.log(
    `Found provider "${providerId}" with ${Object.keys(provider.models).length} models`
  );

  const profiles: Record<string, ModelProfile> = Object.create(null);
  const modelNames = [
    ...new Set([
      ...Object.keys(provider.models),
      ...Object.keys(modelOverrides),
    ]),
  ].sort();
  for (const modelName of modelNames) {
    const model = Object.hasOwn(provider.models, modelName)
      ? provider.models[modelName]
      : undefined;
    profiles[modelName] = applyOverrides(
      model ? modelToProfile(model) : {},
      providerOverrides,
      Object.hasOwn(modelOverrides, modelName)
        ? modelOverrides[modelName]
        : undefined
    );
  }

  const resolvedOutputPath = validatePathInMonorepo(outputPath);
  const oxfmtBin = path.join(
    path.dirname(createRequire(import.meta.url).resolve("oxfmt/package.json")),
    "bin/oxfmt"
  );
  const result = spawnSync(
    process.execPath,
    [oxfmtBin, "--stdin-filepath", resolvedOutputPath],
    {
      cwd: findMonorepoRoot(),
      input: generateTypeScript(profiles),
      encoding: "utf8",
      maxBuffer: 32 * 1024 * 1024,
      timeout: 30000,
    }
  );
  if (result.error || result.status !== 0 || !result.stdout) {
    throw new Error(
      `Failed to format model profiles with oxfmt: ${
        result.error?.message || result.stderr || `exit status ${result.status}`
      }`
    );
  }
  fs.mkdirSync(path.dirname(resolvedOutputPath), { recursive: true });
  fs.writeFileSync(resolvedOutputPath, result.stdout, "utf8");
  console.log(`✅ Generated model profiles file: ${resolvedOutputPath}`);
}
