import * as fs from "node:fs";
import * as path from "node:path";
import { format } from "oxfmt";
import type { ModelProfile } from "@langchain/core/language_models/profile";
import type { Model, ProviderMap } from "./api-schema.js";
import { type ModelProfileOverride, applyOverrides } from "./config.js";
import { validatePathInMonorepo } from "./config.js";

/**
 * Converts a Model from the API schema to a ModelProfile.
 */
function modelToProfile(model: Model): ModelProfile {
  return {
    maxInputTokens: model.limit?.context,
    imageInputs: model.modalities?.input?.includes("image") ?? false,
    audioInputs: model.modalities?.input?.includes("audio") ?? false,
    pdfInputs: model.modalities?.input?.includes("pdf") ?? false,
    videoInputs: model.modalities?.input?.includes("video") ?? false,
    maxOutputTokens: model.limit?.output,
    reasoningOutput: model.reasoning ?? false,
    imageOutputs: model.modalities?.output?.includes("image") ?? false,
    audioOutputs: model.modalities?.output?.includes("audio") ?? false,
    videoOutputs: model.modalities?.output?.includes("video") ?? false,
    toolCalling: model.tool_call ?? false,
    structuredOutput: model.structured_output ?? false,
  };
}

/**
 * Generates a static TypeScript module from model profiles.
 */
function formatPropertyName(key: string): string {
  return /^[$A-Z_a-z][$\w]*$/u.test(key) ? key : JSON.stringify(key);
}

function generateTypeScript(models: Record<string, ModelProfile>): string {
  const modelProfiles = Object.entries(models)
    .map(([modelName, profile]) => {
      const profileProperties = Object.entries(profile)
        .filter(([, value]) => value !== undefined)
        .map(
          ([key, value]) =>
            `    ${formatPropertyName(key)}: ${JSON.stringify(value)},`
        )
        .join("\n");
      return `  ${JSON.stringify(modelName)}: {\n${profileProperties}\n  },`;
    })
    .join("\n");

  return `/**
 * This file was automatically generated by an automated script. Do not edit manually.
 */
import type { ModelProfile } from "@langchain/core/language_models/profile";
const PROFILES: Record<string, ModelProfile> = {
${modelProfiles}
};
export default PROFILES;
`;
}

/**
 * Fetches provider data from the models.dev API.
 */
async function fetchProviderData(): Promise<ProviderMap> {
  const response = await fetch("https://models.dev/api.json", {
    signal: AbortSignal.timeout(30000),
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch models.dev API: ${response.statusText}`);
  }

  return (await response.json()) as ProviderMap;
}

/**
 * Generates model profiles for a provider with overrides applied.
 */
export async function generateModelProfiles(
  providerId: string,
  providerOverrides: ModelProfileOverride,
  modelOverrides: Record<string, ModelProfileOverride>,
  outputPath: string
): Promise<void> {
  console.log(`Fetching provider data from models.dev API...`);
  const data = await fetchProviderData();

  const provider = data[providerId];
  if (!provider) {
    throw new Error(`Provider "${providerId}" not found in models.dev API`);
  }

  console.log(
    `Found provider "${providerId}" with ${
      Object.keys(provider.models).length
    } models`
  );

  const profiles: Record<string, ModelProfile> = {};

  for (const [modelName, modelData] of Object.entries(provider.models)) {
    const baseProfile = modelToProfile(modelData);
    const modelSpecificOverrides = modelOverrides[modelName];

    const finalProfile = applyOverrides(
      baseProfile,
      providerOverrides,
      modelSpecificOverrides
    );

    profiles[modelName] = finalProfile;
  }

  for (const [modelName, modelSpecificOverrides] of Object.entries(
    modelOverrides
  )) {
    if (!(modelName in profiles)) {
      profiles[modelName] = applyOverrides(
        {},
        providerOverrides,
        modelSpecificOverrides
      );
    }
  }

  const typescriptCode = generateTypeScript(profiles);

  // Validate that the output path is within the monorepo (defensive check)
  // outputPath should already be validated by parseConfig, but we validate again for safety
  const resolvedOutputPath = validatePathInMonorepo(outputPath);

  // Ensure the directory exists
  const outputDir = path.dirname(resolvedOutputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Format with Oxfmt using project's configuration
  let formattedCode: string;
  try {
    const result = await format(resolvedOutputPath, typescriptCode);
    if (result.errors.length > 0) {
      throw new Error(result.errors[0]?.message ?? "Unknown oxfmt error");
    }
    formattedCode = result.code;
  } catch (error) {
    console.warn(
      "⚠️ Failed to format code with oxfmt, using unformatted code:",
      error instanceof Error ? error.message : String(error)
    );
    formattedCode = typescriptCode;
  }

  fs.writeFileSync(resolvedOutputPath, formattedCode, "utf-8");
  console.log(`✅ Generated model profiles file: ${resolvedOutputPath}`);
}
