// Auto-generated by lc-secrets plugin. Do not edit manually.

export interface OptionalImportMap {}

export interface SecretMap {
  REDIS_PASSWORD?: string;
  REDIS_URL?: string;
  REDIS_USERNAME?: string;
}
