// Auto-generated by lc-secrets plugin. Do not edit manually.

export interface OptionalImportMap {}

export interface SecretMap {
  YC_API_KEY?: string;
  YC_FOLDER_ID?: string;
  YC_IAM_TOKEN?: string;
}
