import { CallbackManagerForToolRun } from "@langchain/core/callbacks/manager";
import type { ToolCall } from "@langchain/core/messages/tool";
import {
  StructuredTool,
  type ToolParams,
  type ToolRunnableConfig,
} from "@langchain/core/tools";
import { getEnvironmentVariable } from "@langchain/core/utils/env";
import { z } from "zod/v3";
import Exa, {
  ContentsOptions,
  FindSimilarOptions,
  RegularSearchOptions,
} from "exa-js";
import { createExaClient, normalizeSearchArgs } from "./utils.js";

/**
 * Options for the ExaSearchResults tool.
 */
export type ExaSearchRetrieverFields<
  T extends ContentsOptions = { text: true },
> = ToolParams & {
  client?: Exa;
  searchArgs?: RegularSearchOptions & T;
};

const searchInputSchema = z.object({
  query: z.string().describe("Search query to look up"),
  numResults: z.number().int().min(1).max(100).optional(),
  includeDomains: z.array(z.string()).optional(),
  excludeDomains: z.array(z.string()).optional(),
});

const similarInputSchema = z.object({
  url: z.string().url().describe("URL to find similar pages for"),
  numResults: z.number().int().min(1).max(100).optional(),
  includeDomains: z.array(z.string()).optional(),
  excludeDomains: z.array(z.string()).optional(),
});

// The API ignores `false`, so only `true` or an options object is accepted.
const contentOptionSchema = z
  .union([z.literal(true), z.record(z.string(), z.unknown())])
  .optional();

const contentsInputSchema = z.object({
  urls: z.array(z.string().url()).min(1),
  text: contentOptionSchema,
  highlights: contentOptionSchema,
  summary: contentOptionSchema,
  maxAgeHours: z.number().nonnegative().optional(),
});

const answerInputSchema = z.object({
  query: z.string(),
  text: z.boolean().optional(),
  outputSchema: z.record(z.string(), z.unknown()).optional(),
  systemPrompt: z.string().optional(),
  userLocation: z.string().optional(),
});

const agentInputSchema = z.object({
  query: z.string(),
  input: z
    .object({
      data: z.array(z.record(z.string(), z.unknown())).optional(),
      exclusion: z.array(z.record(z.string(), z.unknown())).optional(),
    })
    .catchall(z.unknown())
    .optional(),
  outputSchema: z.record(z.string(), z.unknown()).optional(),
  effort: z.enum(["low", "medium", "high", "xhigh", "auto"]).optional(),
  previousRunId: z.string().optional(),
  dataSources: z
    .array(z.object({ provider: z.string() }).catchall(z.unknown()))
    .optional(),
  timeoutMs: z.number().int().min(1).max(3_600_000).optional(),
  pollInterval: z.number().int().min(500).max(60_000).optional(),
});

/** Build content options for a Contents request; defaults to text. */
function buildContentsOptions(
  options: Omit<z.infer<typeof contentsInputSchema>, "urls">
): ContentsOptions {
  const { text, highlights, summary, maxAgeHours } = options;
  const selected: ContentsOptions = {};
  if (text !== undefined) {
    selected.text = text as ContentsOptions["text"];
  }
  if (highlights !== undefined) {
    selected.highlights = highlights as ContentsOptions["highlights"];
  }
  if (summary !== undefined) {
    selected.summary = summary as ContentsOptions["summary"];
  }
  if (maxAgeHours !== undefined) {
    selected.maxAgeHours = maxAgeHours;
  }
  if (text === undefined && highlights === undefined && summary === undefined) {
    selected.text = true;
  }
  return selected;
}

/**
 * Exa search tool integration.
 *
 * Setup:
 * Install `@langchain/exa` and `exa-js`. You'll also need an API key.
 *
 * ```bash
 * npm install @langchain/exa exa-js
 * ```
 *
 * ## [Constructor args](https://api.js.langchain.com/classes/_langchain_exa.ExaSearchResults.html#constructor)
 *
 * <details open>
 * <summary><strong>Instantiate</strong></summary>
 *
 * ```typescript
 * import { ExaSearchResults } from "@langchain/exa";
 * import Exa from "exa-js";
 *
 * const tool = new ExaSearchResults({
 *   searchArgs: {
 *     numResults: 2,
 *   },
 * });
 * ```
 * </details>
 *
 * <br />
 *
 * <details>
 *
 * <summary><strong>Invocation</strong></summary>
 *
 * ```typescript
 * await tool.invoke("what is the current weather in sf?");
 * ```
 * </details>
 *
 * <br />
 *
 * <details>
 *
 * <summary><strong>Invocation with tool call</strong></summary>
 *
 * ```typescript
 * // This is usually generated by a model, but we'll create a tool call directly for demo purposes.
 * const modelGeneratedToolCall = {
 *   args: {
 *     query: "what is the current weather in sf?",
 *   },
 *   id: "tool_call_id",
 *   name: tool.name,
 *   type: "tool_call",
 * };
 * await tool.invoke(modelGeneratedToolCall);
 * ```
 *
 * ```text
 * ToolMessage {
 *   "content": "...",
 *   "name": "exa_search_results_json",
 *   "additional_kwargs": {},
 *   "response_metadata": {},
 *   "tool_call_id": "tool_call_id"
 * }
 * ```
 * </details>
 */
export class ExaSearchResults<
  T extends ContentsOptions = { text: true },
> extends StructuredTool<
  typeof searchInputSchema,
  z.output<typeof searchInputSchema>,
  z.input<typeof searchInputSchema> | string
> {
  static lc_name(): string {
    return "ExaSearchResults";
  }

  description =
    "A wrapper around Exa Search. Input should be an Exa-optimized query. Output is a JSON array of the query results";

  name = "exa_search_results_json";

  private client: Exa;

  searchArgs?: RegularSearchOptions & T;

  constructor(fields: ExaSearchRetrieverFields<T> = {}) {
    super(fields);
    this.client =
      fields.client ?? createExaClient(getEnvironmentVariable("EXA_API_KEY"));
    this.searchArgs = fields.searchArgs;
  }

  /** Accept a bare query string in addition to structured input. */
  call<
    TArg extends string | z.input<typeof searchInputSchema> | ToolCall,
    TConfig extends ToolRunnableConfig | undefined,
  >(arg: TArg, callbacks?: TConfig) {
    const structuredArg = (
      typeof arg === "string" ? { query: arg } : arg
    ) as TArg;
    return super.call(structuredArg, callbacks);
  }

  protected async _call(
    input: string | z.infer<typeof searchInputSchema>,
    _runManager?: CallbackManagerForToolRun
  ): Promise<string> {
    const args = typeof input === "string" ? { query: input } : input;
    const { query, ...inputArgs } = args;
    return JSON.stringify(
      await this.client.search(query, {
        ...normalizeSearchArgs(this.searchArgs),
        ...inputArgs,
      } as RegularSearchOptions & { contents: ContentsOptions })
    );
  }

  schema = searchInputSchema;
}

/**
 * Wrapper around Exa's `/findSimilar` endpoint.
 *
 * @deprecated Exa has deprecated `/findSimilar`. Prefer {@link ExaSearchResults}.
 * This tool remains available for compatibility.
 */
export class ExaFindSimilarResults<
  T extends ContentsOptions = { text: true },
> extends StructuredTool<
  typeof similarInputSchema,
  z.output<typeof similarInputSchema>,
  z.input<typeof similarInputSchema> | string
> {
  static lc_name(): string {
    return "ExaFindSimilarResults";
  }

  description =
    "Deprecated. Prefer exa_search_results_json. Finds pages similar to a URL via Exa's deprecated /findSimilar endpoint.";

  name = "exa_find_similar_results_json";

  private client: Exa;

  searchArgs?: RegularSearchOptions & T;

  constructor(fields: ExaSearchRetrieverFields<T> = {}) {
    super(fields);
    this.client =
      fields.client ?? createExaClient(getEnvironmentVariable("EXA_API_KEY"));
    this.searchArgs = {
      text: true,
      ...fields.searchArgs,
    } as RegularSearchOptions & T;
  }

  /** Accept a bare URL string in addition to structured input. */
  call<
    TArg extends string | z.input<typeof similarInputSchema> | ToolCall,
    TConfig extends ToolRunnableConfig | undefined,
  >(arg: TArg, callbacks?: TConfig) {
    const structuredArg = (
      typeof arg === "string" ? { url: arg } : arg
    ) as TArg;
    return super.call(structuredArg, callbacks);
  }

  protected async _call(
    input: string | z.infer<typeof similarInputSchema>,
    _runManager?: CallbackManagerForToolRun
  ): Promise<string> {
    const args = typeof input === "string" ? { url: input } : input;
    const { url, ...inputArgs } = args;
    const {
      type: _type,
      contents,
      ...similarArgs
    } = (this.searchArgs ?? {}) as {
      type?: string;
      contents?: ContentsOptions;
    } & Record<string, unknown>;
    return JSON.stringify(
      await this.client.findSimilarAndContents(url, {
        ...similarArgs,
        ...contents,
        ...inputArgs,
      } as FindSimilarOptions & ContentsOptions)
    );
  }

  schema = similarInputSchema;
}

type ExaToolFields = ToolParams & { client?: Exa };

abstract class ExaApiTool<T extends z.ZodType> extends StructuredTool<T> {
  protected client: Exa;

  constructor(fields: ExaToolFields = {}) {
    super(fields);
    this.client =
      fields.client ?? createExaClient(getEnvironmentVariable("EXA_API_KEY"));
  }
}

/** Extract text, highlights, or summaries from URLs with Exa. */
export class ExaContents extends ExaApiTool<typeof contentsInputSchema> {
  name = "exa_contents";
  description = "Extract contents from one or more URLs using Exa.";
  schema = contentsInputSchema;

  protected async _call(
    input: z.infer<typeof contentsInputSchema>
  ): Promise<string> {
    const { urls, ...options } = input;
    return JSON.stringify(
      await this.client.getContents(urls, buildContentsOptions(options))
    );
  }
}

/** Answer a question with a grounded Exa answer and citations. */
export class ExaAnswer extends ExaApiTool<typeof answerInputSchema> {
  name = "exa_answer";
  description =
    "Answer a question with a grounded answer and citations from Exa.";
  schema = answerInputSchema;

  protected async _call(
    input: z.infer<typeof answerInputSchema>
  ): Promise<string> {
    const { query, ...options } = input;
    return JSON.stringify(await this.client.answer(query, options));
  }
}

/** Run Exa's asynchronous multi-step Agent workflow. */
export class ExaAgent extends ExaApiTool<typeof agentInputSchema> {
  name = "exa_agent";
  description =
    "Run Exa Agent for a long-running, multi-step grounded workflow.";
  schema = agentInputSchema;

  protected async _call(
    input: z.infer<typeof agentInputSchema>
  ): Promise<string> {
    const { timeoutMs = 3_600_000, pollInterval = 1_000, ...params } = input;
    const run = await this.client.agent.runs.create(params);
    const result = await this.client.agent.runs.pollUntilFinished(run.id, {
      timeoutMs,
      pollInterval,
    });
    return JSON.stringify(result);
  }
}
