// Auto-generated by lc-secrets plugin. Do not edit manually.

export interface OptionalImportMap {}

export interface SecretMap {
  AZURE_COSMOSDB_MONGODB_CONNECTION_STRING?: string;
  AZURE_COSMOSDB_NOSQL_CONNECTION_STRING?: string;
}
