import { Tools as ToolsContentBlock } from "./tools.js";
import { Multimodal as MultimodalContentBlock } from "./multimodal.js";

export interface ContentBlock {
  /**
   * Type of the content block
   */
  readonly type: string;
  /**
   * Content block identifier, which can be either
   *  - generated by the provider (e.g., a provider-specific ID)
   *  - generated by LangChain upon creation (a uuid prefixed with 'lc-')
   */
  id?: string;
}

// eslint-disable-next-line @typescript-eslint/no-namespace
export declare namespace ContentBlock {
  /**
   * Annotation for citing data from a document.
   */
  interface Citation extends ContentBlock {
    /**
     * Type of the content block
     */
    readonly type: "citation";
    /**
     * URL of the document source
     */
    url?: string;
    /**
     * Source document title.
     *
     * For example, the page title for a web page or the title of a paper.
     */
    title?: string;
    /**
     * Start index of the **response text** for which the annotation applies.
     *
     * @see {TextContentBlock.text}
     */
    startIndex?: number;
    /**
     * End index of the **response text** for which the annotation applies.
     *
     * @see {TextContentBlock.text}
     */
    endIndex?: number;
    /**
     * Excerpt of source text being cited.
     */
    citedText?: string;
  }

  /**
   * Text output from a LLM.
   *
   * This typically represents the main text content of a message, such as the response
   * from a language model or the text of a user message.
   */
  interface TextContentBlock extends ContentBlock {
    /**
     * Type of the content block
     */
    readonly type: "text";
    /**
     * Block text.
     */
    text: string;
    /**
     * Index of block in aggregate response. Used during streaming.
     */
    index?: number;
    /**
     * Citations and other annotations.
     */
    annotations?: Citation[];
  }

  /**
   * Reasoning output from a LLM.
   */
  interface ReasoningContentBlock extends ContentBlock {
    /**
     * Type of the content block
     */
    readonly type: "reasoning";
    /**
     * Reasoning text.
     *
     * Either the thought summary or the raw reasoning text itself.
     * This is often parsed from `<think>` tags in the model's response.
     */
    reasoning: string;
    /**
     * Index of block in aggregate response. Used during streaming.
     */
    index?: number;
  }

  export import Tools = ToolsContentBlock;
  export import Multimodal = MultimodalContentBlock;
  export type Standard =
    | TextContentBlock
    | ReasoningContentBlock
    | Tools.ContentBlock
    | Multimodal.ContentBlock;
}
