import type { OpenAI as OpenAIClient } from "openai";
import {
  BaseMessage,
  ChatMessage,
  ContentBlock,
  Data,
} from "@langchain/core/messages";

export const iife = <T>(fn: () => T) => fn();

export function isReasoningModel(model?: string) {
  if (!model) return false;
  if (/^o\d/.test(model ?? "")) return true;
  if (model.startsWith("gpt-5") && !model.startsWith("gpt-5-chat")) return true;
  if (model.startsWith("gpt-6") && !model.startsWith("gpt-6-chat")) return true;
  return false;
}

export function extractGenericMessageCustomRole(message: ChatMessage) {
  if (
    message.role !== "system" &&
    message.role !== "developer" &&
    message.role !== "assistant" &&
    message.role !== "user" &&
    message.role !== "function" &&
    message.role !== "tool"
  ) {
    console.warn(`Unknown message role: ${message.role}`);
  }

  return message.role as OpenAIClient.ChatCompletionRole;
}

export function getFilenameFromMetadata(
  block:
    | ContentBlock.Multimodal.File
    | ContentBlock.Multimodal.Video
    | Data.StandardFileBlock
): string | undefined {
  return (block.metadata?.filename ??
    block.metadata?.name ??
    block.metadata?.title) as string;
}

export const LC_AUTOGENERATED_FILENAME = "LC_AUTOGENERATED";

export function getRequiredFilenameFromMetadata(
  block:
    | ContentBlock.Multimodal.File
    | ContentBlock.Multimodal.Video
    | Data.StandardFileBlock
): string {
  const filename = (block.metadata?.filename ??
    block.metadata?.name ??
    block.metadata?.title) as string;

  if (!filename) {
    console.warn(
      "OpenAI may require a filename for file uploads. Specify a filename " +
        "in the content block metadata, e.g.: { type: 'file', mimeType: " +
        "'...', data: '...', metadata: { filename: 'my-file.pdf' } }. " +
        "Using placeholder filename 'LC_AUTOGENERATED'."
    );
    return LC_AUTOGENERATED_FILENAME;
  }

  return filename;
}
export function messageToOpenAIRole(
  message: BaseMessage
): OpenAIClient.ChatCompletionRole {
  const type = message._getType();
  switch (type) {
    case "system":
      return "system";
    case "ai":
      return "assistant";
    case "human":
      return "user";
    case "function":
      return "function";
    case "tool":
      return "tool";
    case "generic": {
      if (!ChatMessage.isInstance(message))
        throw new Error("Invalid generic chat message");
      return extractGenericMessageCustomRole(message);
    }
    default:
      throw new Error(`Unknown message type: ${type}`);
  }
}

// Legacy OpenAI chat model families that default to the Chat Completions API;
// trailing date snapshot suffixes are stripped before matching.
const LEGACY_CHAT_COMPLETIONS_FAMILIES: readonly string[] = [
  "gpt-3.5-turbo",
  "gpt-3.5-turbo-0125",
  "gpt-3.5-turbo-1106",
  "gpt-3.5-turbo-0613",
  "gpt-3.5-turbo-0301",
  "gpt-3.5-turbo-16k",
  "gpt-3.5-turbo-16k-0613",
  "gpt-4",
  "gpt-4-0314",
  "gpt-4-0613",
  "gpt-4-32k",
  "gpt-4-32k-0314",
  "gpt-4-32k-0613",
  "gpt-4-turbo",
  "gpt-4-turbo-preview",
  "gpt-4-0125-preview",
  "gpt-4-1106-preview",
  "gpt-4-vision-preview",
  "gpt-4-1106-vision-preview",
  "gpt-4.5-preview",
  "gpt-4o",
  "gpt-4o-mini",
  "gpt-4o-audio-preview",
  "gpt-4o-mini-audio-preview",
  "gpt-4o-search-preview",
  "gpt-4o-mini-search-preview",
  "chatgpt-4o-latest",
  "gpt-4.1",
  "gpt-4.1-mini",
  "gpt-4.1-nano",
  "o1",
  "o1-preview",
  "o1-mini",
  "o3",
  "o3-mini",
  "o4-mini",
  "gpt-audio",
  "gpt-audio-mini",
  "gpt-audio-1.5",
  "gpt-5-search-api",
  "chat-latest",
  "gpt-5-chat-latest",
  "gpt-5.1-chat-latest",
  "gpt-5.2-chat-latest",
  "gpt-5.3-chat-latest",
  "gpt-5",
  "gpt-5-mini",
  "gpt-5-nano",
  "gpt-5.1",
  "gpt-5.2",
  "gpt-5.4",
  "gpt-5.4-mini",
  "gpt-5.4-nano",
  "gpt-5.5",
];

export function _modelPrefersResponsesAPI(model: string): boolean {
  const base = (
    model.startsWith("ft:") ? (model.split(":")[1] ?? model) : model
  ).replace(/-\d{4}-\d{2}-\d{2}$/, "");
  return !LEGACY_CHAT_COMPLETIONS_FAMILIES.includes(base);
}
