import { PromptTemplate } from "../../prompts/prompt.js";

export const PREDICT_NEXT_USER_MESSAGE_PROMPT = PromptTemplate.fromTemplate(`
You have been tasked with coming up with insights and data-points based on a chat history between a human and an AI.
Given the user's chat history provide the following:
- Concise reasoning about the users internal mental state.
- Likely possibility for the next user response.
- A concise list of any additional data that would be useful to improve prediction.
--------
Chat History: {chat_history}`);

export const PREDICTION_VIOLATIONS_PROMPT =
  PromptTemplate.fromTemplate(`You are analyzing some data points generated by an LLM and are tasked to derive any violations between expected outputs and actual output.
You are provided with the following data-points:
- The predicted output the LLM generated based on what it believed the user would say.
- The actual output the user said.
- Key data about the user, their mental state, and any other insights derived from the chat history.
--------
Predicted Output: {predicted_output}
--------
Actual Output: {actual_output}
--------
User Insights: {user_insights}
--------
Respond with:
- How exactly was the expectation violated? Which parts were wrong?
- If there were errors with the prediction, what were they and why?`);

export const GENERATE_REVISED_PREDICTION_PROMPT = PromptTemplate.fromTemplate(`
You have been tasked with revising a prediction on what a user might say in a chat conversation.
--------
Your previous prediction: {prediction}
--------
Ways in which your prediction was off: {explained_prediction_errors}
--------
Key insights to the user: {user_insights}
--------
Given the above, revise your prediction to be more accurate.
Revised Prediction:`);

export const GENERATE_FACTS_PROMPT = PromptTemplate.fromTemplate(`
Given a user message, an LLM generated prediction of what that message might be, and a list of violations which the prediction made compared to the actual message, generate a fact about the user, relevant to the users message.
--------
Prediction violations: {prediction_violations}
--------
Revised prediction: {prediction}
--------
Actual user message: {user_message}
--------
Relevant fact:`);
