/** Auto-generated by import-constants plugin. Do not edit manually */

export const optionalImportEntrypoints: string[] = [
  "langchain_langchain/chat_models/universal",
  "langchain_langchain/cache/file_system",
  "langchain_langchain/storage/file_system",
  "langchain_langchain/hub",
  "langchain_langchain/hub/node",
];
