// Auto-generated by `scripts/create-entrypoints.js`. Do not edit manually.

export async function getDynamicImportMap() {
  const chat_models__fireworks: Record<string, any> = {};
  try {
    const dynamicImports = await import(
      "@langchain/community/chat_models/fireworks"
    );
    chat_models__fireworks.ChatFireworks = dynamicImports.ChatFireworks;
  } catch (e) {}

  const llms__fireworks: Record<string, any> = {};
  try {
    const dynamicImports = await import("@langchain/community/llms/fireworks");
    llms__fireworks.Fireworks = dynamicImports.Fireworks;
  } catch (e) {}

  const chat_models__bedrock: Record<string, any> = {};
  try {
    const dynamicImports = await import(
      "@langchain/community/chat_models/bedrock"
    );
    chat_models__bedrock.BedrockChat = dynamicImports.BedrockChat;
  } catch (e) {}

  const llms__bedrock: Record<string, any> = {};
  try {
    const dynamicImports = await import("@langchain/community/llms/bedrock");
    llms__bedrock.Bedrock = dynamicImports.Bedrock;
  } catch (e) {}

  const chat_models__anthropic: Record<string, any> = {};
  try {
    const dynamicImports = await import("@langchain/anthropic");
    chat_models__anthropic.ChatAnthropic = dynamicImports.ChatAnthropic;
  } catch (e) {}

  const llms__replicate: Record<string, any> = {};
  try {
    const dynamicImports = await import("@langchain/community/llms/replicate");
    llms__replicate.Replicate = dynamicImports.Replicate;
  } catch (e) {}
  return {
    chat_models__fireworks,
    llms__fireworks,
    chat_models__bedrock,
    llms__bedrock,
    chat_models__anthropic,
    llms__replicate,
  };
}
