// Auto-generated by lc-secrets plugin. Do not edit manually.

export interface OptionalImportMap {}

export interface SecretMap {
  AZURE_OPENAI_API_KEY?: string;
  OPENAI_API_KEY?: string;
  OPENAI_ORGANIZATION?: string;
}
