// Auto-generated by lc-secrets plugin. Do not edit manually.

export interface OptionalImportMap {}

export interface SecretMap {
  QIANFAN_ACCESS_KEY?: string;
  QIANFAN_AK?: string;
  QIANFAN_SECRET_KEY?: string;
  QIANFAN_SK?: string;
}
