// Auto-generated by `scripts/create-entrypoints.js`. Do not edit manually.

export interface OptionalImportMap {
  "@langchain/community/tools/aws_lambda"?:
    | typeof import("../tools/aws_lambda.js")
    | Promise<typeof import("../tools/aws_lambda.js")>;
  "@langchain/community/tools/aws_sfn"?:
    | typeof import("../tools/aws_sfn.js")
    | Promise<typeof import("../tools/aws_sfn.js")>;
  "@langchain/community/tools/discord"?:
    | typeof import("../tools/discord.js")
    | Promise<typeof import("../tools/discord.js")>;
  "@langchain/community/tools/gmail"?:
    | typeof import("../tools/gmail/index.js")
    | Promise<typeof import("../tools/gmail/index.js")>;
  "@langchain/community/agents/toolkits/aws_sfn"?:
    | typeof import("../agents/toolkits/aws_sfn.js")
    | Promise<typeof import("../agents/toolkits/aws_sfn.js")>;
  "@langchain/community/embeddings/bedrock"?:
    | typeof import("../embeddings/bedrock.js")
    | Promise<typeof import("../embeddings/bedrock.js")>;
  "@langchain/community/embeddings/cloudflare_workersai"?:
    | typeof import("../embeddings/cloudflare_workersai.js")
    | Promise<typeof import("../embeddings/cloudflare_workersai.js")>;
  "@langchain/community/embeddings/cohere"?:
    | typeof import("../embeddings/cohere.js")
    | Promise<typeof import("../embeddings/cohere.js")>;
  "@langchain/community/embeddings/googlepalm"?:
    | typeof import("../embeddings/googlepalm.js")
    | Promise<typeof import("../embeddings/googlepalm.js")>;
  "@langchain/community/embeddings/googlevertexai"?:
    | typeof import("../embeddings/googlevertexai.js")
    | Promise<typeof import("../embeddings/googlevertexai.js")>;
  "@langchain/community/embeddings/gradient_ai"?:
    | typeof import("../embeddings/gradient_ai.js")
    | Promise<typeof import("../embeddings/gradient_ai.js")>;
  "@langchain/community/embeddings/hf"?:
    | typeof import("../embeddings/hf.js")
    | Promise<typeof import("../embeddings/hf.js")>;
  "@langchain/community/embeddings/hf_transformers"?:
    | typeof import("../embeddings/hf_transformers.js")
    | Promise<typeof import("../embeddings/hf_transformers.js")>;
  "@langchain/community/embeddings/llama_cpp"?:
    | typeof import("../embeddings/llama_cpp.js")
    | Promise<typeof import("../embeddings/llama_cpp.js")>;
  "@langchain/community/embeddings/tensorflow"?:
    | typeof import("../embeddings/tensorflow.js")
    | Promise<typeof import("../embeddings/tensorflow.js")>;
  "@langchain/community/llms/bedrock"?:
    | typeof import("../llms/bedrock/index.js")
    | Promise<typeof import("../llms/bedrock/index.js")>;
  "@langchain/community/llms/bedrock/web"?:
    | typeof import("../llms/bedrock/web.js")
    | Promise<typeof import("../llms/bedrock/web.js")>;
  "@langchain/community/llms/cohere"?:
    | typeof import("../llms/cohere.js")
    | Promise<typeof import("../llms/cohere.js")>;
  "@langchain/community/llms/googlepalm"?:
    | typeof import("../llms/googlepalm.js")
    | Promise<typeof import("../llms/googlepalm.js")>;
  "@langchain/community/llms/googlevertexai"?:
    | typeof import("../llms/googlevertexai/index.js")
    | Promise<typeof import("../llms/googlevertexai/index.js")>;
  "@langchain/community/llms/googlevertexai/web"?:
    | typeof import("../llms/googlevertexai/web.js")
    | Promise<typeof import("../llms/googlevertexai/web.js")>;
  "@langchain/community/llms/gradient_ai"?:
    | typeof import("../llms/gradient_ai.js")
    | Promise<typeof import("../llms/gradient_ai.js")>;
  "@langchain/community/llms/hf"?:
    | typeof import("../llms/hf.js")
    | Promise<typeof import("../llms/hf.js")>;
  "@langchain/community/llms/llama_cpp"?:
    | typeof import("../llms/llama_cpp.js")
    | Promise<typeof import("../llms/llama_cpp.js")>;
  "@langchain/community/llms/portkey"?:
    | typeof import("../llms/portkey.js")
    | Promise<typeof import("../llms/portkey.js")>;
  "@langchain/community/llms/raycast"?:
    | typeof import("../llms/raycast.js")
    | Promise<typeof import("../llms/raycast.js")>;
  "@langchain/community/llms/replicate"?:
    | typeof import("../llms/replicate.js")
    | Promise<typeof import("../llms/replicate.js")>;
  "@langchain/community/llms/sagemaker_endpoint"?:
    | typeof import("../llms/sagemaker_endpoint.js")
    | Promise<typeof import("../llms/sagemaker_endpoint.js")>;
  "@langchain/community/llms/watsonx_ai"?:
    | typeof import("../llms/watsonx_ai.js")
    | Promise<typeof import("../llms/watsonx_ai.js")>;
  "@langchain/community/llms/writer"?:
    | typeof import("../llms/writer.js")
    | Promise<typeof import("../llms/writer.js")>;
  "@langchain/community/vectorstores/analyticdb"?:
    | typeof import("../vectorstores/analyticdb.js")
    | Promise<typeof import("../vectorstores/analyticdb.js")>;
  "@langchain/community/vectorstores/cassandra"?:
    | typeof import("../vectorstores/cassandra.js")
    | Promise<typeof import("../vectorstores/cassandra.js")>;
  "@langchain/community/vectorstores/chroma"?:
    | typeof import("../vectorstores/chroma.js")
    | Promise<typeof import("../vectorstores/chroma.js")>;
  "@langchain/community/vectorstores/clickhouse"?:
    | typeof import("../vectorstores/clickhouse.js")
    | Promise<typeof import("../vectorstores/clickhouse.js")>;
  "@langchain/community/vectorstores/closevector/node"?:
    | typeof import("../vectorstores/closevector/node.js")
    | Promise<typeof import("../vectorstores/closevector/node.js")>;
  "@langchain/community/vectorstores/closevector/web"?:
    | typeof import("../vectorstores/closevector/web.js")
    | Promise<typeof import("../vectorstores/closevector/web.js")>;
  "@langchain/community/vectorstores/cloudflare_vectorize"?:
    | typeof import("../vectorstores/cloudflare_vectorize.js")
    | Promise<typeof import("../vectorstores/cloudflare_vectorize.js")>;
  "@langchain/community/vectorstores/convex"?:
    | typeof import("../vectorstores/convex.js")
    | Promise<typeof import("../vectorstores/convex.js")>;
  "@langchain/community/vectorstores/elasticsearch"?:
    | typeof import("../vectorstores/elasticsearch.js")
    | Promise<typeof import("../vectorstores/elasticsearch.js")>;
  "@langchain/community/vectorstores/faiss"?:
    | typeof import("../vectorstores/faiss.js")
    | Promise<typeof import("../vectorstores/faiss.js")>;
  "@langchain/community/vectorstores/googlevertexai"?:
    | typeof import("../vectorstores/googlevertexai.js")
    | Promise<typeof import("../vectorstores/googlevertexai.js")>;
  "@langchain/community/vectorstores/hnswlib"?:
    | typeof import("../vectorstores/hnswlib.js")
    | Promise<typeof import("../vectorstores/hnswlib.js")>;
  "@langchain/community/vectorstores/lancedb"?:
    | typeof import("../vectorstores/lancedb.js")
    | Promise<typeof import("../vectorstores/lancedb.js")>;
  "@langchain/community/vectorstores/milvus"?:
    | typeof import("../vectorstores/milvus.js")
    | Promise<typeof import("../vectorstores/milvus.js")>;
  "@langchain/community/vectorstores/momento_vector_index"?:
    | typeof import("../vectorstores/momento_vector_index.js")
    | Promise<typeof import("../vectorstores/momento_vector_index.js")>;
  "@langchain/community/vectorstores/mongodb_atlas"?:
    | typeof import("../vectorstores/mongodb_atlas.js")
    | Promise<typeof import("../vectorstores/mongodb_atlas.js")>;
  "@langchain/community/vectorstores/myscale"?:
    | typeof import("../vectorstores/myscale.js")
    | Promise<typeof import("../vectorstores/myscale.js")>;
  "@langchain/community/vectorstores/neo4j_vector"?:
    | typeof import("../vectorstores/neo4j_vector.js")
    | Promise<typeof import("../vectorstores/neo4j_vector.js")>;
  "@langchain/community/vectorstores/opensearch"?:
    | typeof import("../vectorstores/opensearch.js")
    | Promise<typeof import("../vectorstores/opensearch.js")>;
  "@langchain/community/vectorstores/pgvector"?:
    | typeof import("../vectorstores/pgvector.js")
    | Promise<typeof import("../vectorstores/pgvector.js")>;
  "@langchain/community/vectorstores/pinecone"?:
    | typeof import("../vectorstores/pinecone.js")
    | Promise<typeof import("../vectorstores/pinecone.js")>;
  "@langchain/community/vectorstores/qdrant"?:
    | typeof import("../vectorstores/qdrant.js")
    | Promise<typeof import("../vectorstores/qdrant.js")>;
  "@langchain/community/vectorstores/redis"?:
    | typeof import("../vectorstores/redis.js")
    | Promise<typeof import("../vectorstores/redis.js")>;
  "@langchain/community/vectorstores/rockset"?:
    | typeof import("../vectorstores/rockset.js")
    | Promise<typeof import("../vectorstores/rockset.js")>;
  "@langchain/community/vectorstores/singlestore"?:
    | typeof import("../vectorstores/singlestore.js")
    | Promise<typeof import("../vectorstores/singlestore.js")>;
  "@langchain/community/vectorstores/supabase"?:
    | typeof import("../vectorstores/supabase.js")
    | Promise<typeof import("../vectorstores/supabase.js")>;
  "@langchain/community/vectorstores/tigris"?:
    | typeof import("../vectorstores/tigris.js")
    | Promise<typeof import("../vectorstores/tigris.js")>;
  "@langchain/community/vectorstores/typeorm"?:
    | typeof import("../vectorstores/typeorm.js")
    | Promise<typeof import("../vectorstores/typeorm.js")>;
  "@langchain/community/vectorstores/typesense"?:
    | typeof import("../vectorstores/typesense.js")
    | Promise<typeof import("../vectorstores/typesense.js")>;
  "@langchain/community/vectorstores/usearch"?:
    | typeof import("../vectorstores/usearch.js")
    | Promise<typeof import("../vectorstores/usearch.js")>;
  "@langchain/community/vectorstores/vercel_postgres"?:
    | typeof import("../vectorstores/vercel_postgres.js")
    | Promise<typeof import("../vectorstores/vercel_postgres.js")>;
  "@langchain/community/vectorstores/voy"?:
    | typeof import("../vectorstores/voy.js")
    | Promise<typeof import("../vectorstores/voy.js")>;
  "@langchain/community/vectorstores/weaviate"?:
    | typeof import("../vectorstores/weaviate.js")
    | Promise<typeof import("../vectorstores/weaviate.js")>;
  "@langchain/community/vectorstores/xata"?:
    | typeof import("../vectorstores/xata.js")
    | Promise<typeof import("../vectorstores/xata.js")>;
  "@langchain/community/vectorstores/zep"?:
    | typeof import("../vectorstores/zep.js")
    | Promise<typeof import("../vectorstores/zep.js")>;
  "@langchain/community/chat_models/bedrock"?:
    | typeof import("../chat_models/bedrock/index.js")
    | Promise<typeof import("../chat_models/bedrock/index.js")>;
  "@langchain/community/chat_models/bedrock/web"?:
    | typeof import("../chat_models/bedrock/web.js")
    | Promise<typeof import("../chat_models/bedrock/web.js")>;
  "@langchain/community/chat_models/googlevertexai"?:
    | typeof import("../chat_models/googlevertexai/index.js")
    | Promise<typeof import("../chat_models/googlevertexai/index.js")>;
  "@langchain/community/chat_models/googlevertexai/web"?:
    | typeof import("../chat_models/googlevertexai/web.js")
    | Promise<typeof import("../chat_models/googlevertexai/web.js")>;
  "@langchain/community/chat_models/googlepalm"?:
    | typeof import("../chat_models/googlepalm.js")
    | Promise<typeof import("../chat_models/googlepalm.js")>;
  "@langchain/community/chat_models/iflytek_xinghuo"?:
    | typeof import("../chat_models/iflytek_xinghuo/index.js")
    | Promise<typeof import("../chat_models/iflytek_xinghuo/index.js")>;
  "@langchain/community/chat_models/iflytek_xinghuo/web"?:
    | typeof import("../chat_models/iflytek_xinghuo/web.js")
    | Promise<typeof import("../chat_models/iflytek_xinghuo/web.js")>;
  "@langchain/community/chat_models/llama_cpp"?:
    | typeof import("../chat_models/llama_cpp.js")
    | Promise<typeof import("../chat_models/llama_cpp.js")>;
  "@langchain/community/chat_models/portkey"?:
    | typeof import("../chat_models/portkey.js")
    | Promise<typeof import("../chat_models/portkey.js")>;
  "@langchain/community/callbacks/handlers/llmonitor"?:
    | typeof import("../callbacks/handlers/llmonitor.js")
    | Promise<typeof import("../callbacks/handlers/llmonitor.js")>;
  "@langchain/community/retrievers/amazon_kendra"?:
    | typeof import("../retrievers/amazon_kendra.js")
    | Promise<typeof import("../retrievers/amazon_kendra.js")>;
  "@langchain/community/retrievers/metal"?:
    | typeof import("../retrievers/metal.js")
    | Promise<typeof import("../retrievers/metal.js")>;
  "@langchain/community/retrievers/supabase"?:
    | typeof import("../retrievers/supabase.js")
    | Promise<typeof import("../retrievers/supabase.js")>;
  "@langchain/community/retrievers/zep"?:
    | typeof import("../retrievers/zep.js")
    | Promise<typeof import("../retrievers/zep.js")>;
  "@langchain/community/graphs/neo4j_graph"?:
    | typeof import("../graphs/neo4j_graph.js")
    | Promise<typeof import("../graphs/neo4j_graph.js")>;
  "@langchain/community/document_transformers/html_to_text"?:
    | typeof import("../document_transformers/html_to_text.js")
    | Promise<typeof import("../document_transformers/html_to_text.js")>;
  "@langchain/community/document_transformers/mozilla_readability"?:
    | typeof import("../document_transformers/mozilla_readability.js")
    | Promise<typeof import("../document_transformers/mozilla_readability.js")>;
  "@langchain/community/storage/convex"?:
    | typeof import("../storage/convex.js")
    | Promise<typeof import("../storage/convex.js")>;
  "@langchain/community/storage/ioredis"?:
    | typeof import("../storage/ioredis.js")
    | Promise<typeof import("../storage/ioredis.js")>;
  "@langchain/community/storage/upstash_redis"?:
    | typeof import("../storage/upstash_redis.js")
    | Promise<typeof import("../storage/upstash_redis.js")>;
  "@langchain/community/storage/vercel_kv"?:
    | typeof import("../storage/vercel_kv.js")
    | Promise<typeof import("../storage/vercel_kv.js")>;
  "@langchain/community/stores/message/cassandra"?:
    | typeof import("../stores/message/cassandra.js")
    | Promise<typeof import("../stores/message/cassandra.js")>;
  "@langchain/community/stores/message/cloudflare_d1"?:
    | typeof import("../stores/message/cloudflare_d1.js")
    | Promise<typeof import("../stores/message/cloudflare_d1.js")>;
  "@langchain/community/stores/message/convex"?:
    | typeof import("../stores/message/convex.js")
    | Promise<typeof import("../stores/message/convex.js")>;
  "@langchain/community/stores/message/dynamodb"?:
    | typeof import("../stores/message/dynamodb.js")
    | Promise<typeof import("../stores/message/dynamodb.js")>;
  "@langchain/community/stores/message/firestore"?:
    | typeof import("../stores/message/firestore.js")
    | Promise<typeof import("../stores/message/firestore.js")>;
  "@langchain/community/stores/message/ioredis"?:
    | typeof import("../stores/message/ioredis.js")
    | Promise<typeof import("../stores/message/ioredis.js")>;
  "@langchain/community/stores/message/momento"?:
    | typeof import("../stores/message/momento.js")
    | Promise<typeof import("../stores/message/momento.js")>;
  "@langchain/community/stores/message/mongodb"?:
    | typeof import("../stores/message/mongodb.js")
    | Promise<typeof import("../stores/message/mongodb.js")>;
  "@langchain/community/stores/message/planetscale"?:
    | typeof import("../stores/message/planetscale.js")
    | Promise<typeof import("../stores/message/planetscale.js")>;
  "@langchain/community/stores/message/redis"?:
    | typeof import("../stores/message/redis.js")
    | Promise<typeof import("../stores/message/redis.js")>;
  "@langchain/community/stores/message/upstash_redis"?:
    | typeof import("../stores/message/upstash_redis.js")
    | Promise<typeof import("../stores/message/upstash_redis.js")>;
  "@langchain/community/stores/message/xata"?:
    | typeof import("../stores/message/xata.js")
    | Promise<typeof import("../stores/message/xata.js")>;
  "@langchain/community/memory/motorhead_memory"?:
    | typeof import("../memory/motorhead_memory.js")
    | Promise<typeof import("../memory/motorhead_memory.js")>;
  "@langchain/community/memory/zep"?:
    | typeof import("../memory/zep.js")
    | Promise<typeof import("../memory/zep.js")>;
  "@langchain/community/util/convex"?:
    | typeof import("../utils/convex.js")
    | Promise<typeof import("../utils/convex.js")>;
}

export interface SecretMap {
  AWS_ACCESS_KEY_ID?: string;
  AWS_SECRETE_ACCESS_KEY?: string;
  AWS_SECRET_ACCESS_KEY?: string;
  AWS_SESSION_TOKEN?: string;
  BAIDU_API_KEY?: string;
  BAIDU_SECRET_KEY?: string;
  BEDROCK_AWS_ACCESS_KEY_ID?: string;
  BEDROCK_AWS_SECRET_ACCESS_KEY?: string;
  CLOUDFLARE_API_TOKEN?: string;
  COHERE_API_KEY?: string;
  DATABERRY_API_KEY?: string;
  FIREWORKS_API_KEY?: string;
  GOOGLE_API_KEY?: string;
  GOOGLE_PALM_API_KEY?: string;
  GOOGLE_PLACES_API_KEY?: string;
  GOOGLE_VERTEX_AI_WEB_CREDENTIALS?: string;
  GRADIENT_ACCESS_TOKEN?: string;
  GRADIENT_WORKSPACE_ID?: string;
  HUGGINGFACEHUB_API_KEY?: string;
  IBM_CLOUD_API_KEY?: string;
  IFLYTEK_API_KEY?: string;
  IFLYTEK_API_SECRET?: string;
  MILVUS_PASSWORD?: string;
  MILVUS_SSL?: string;
  MILVUS_USERNAME?: string;
  MINIMAX_API_KEY?: string;
  MINIMAX_GROUP_ID?: string;
  PLANETSCALE_DATABASE_URL?: string;
  PLANETSCALE_HOST?: string;
  PLANETSCALE_PASSWORD?: string;
  PLANETSCALE_USERNAME?: string;
  QDRANT_API_KEY?: string;
  QDRANT_URL?: string;
  REDIS_PASSWORD?: string;
  REDIS_URL?: string;
  REDIS_USERNAME?: string;
  REPLICATE_API_TOKEN?: string;
  SEARXNG_API_BASE?: string;
  UPSTASH_REDIS_REST_TOKEN?: string;
  UPSTASH_REDIS_REST_URL?: string;
  VECTARA_API_KEY?: string;
  VECTARA_CORPUS_ID?: string;
  VECTARA_CUSTOMER_ID?: string;
  WATSONX_PROJECT_ID?: string;
  WRITER_API_KEY?: string;
  WRITER_ORG_ID?: string;
  YC_API_KEY?: string;
  YC_IAM_TOKEN?: string;
  ZEP_API_KEY?: string;
  ZEP_API_URL?: string;
}
