name: publish-preview

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-preview-packages:
    name: Publish Preview Packages
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'publish-preview') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v4

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Detect packages from changed changesets
        if: ${{ github.event_name == 'pull_request' }}
        id: changed_packages
        run: .github/workflows/scripts/get-changed-changeset-package-paths.sh "${{ github.event.pull_request.base.sha }}" "${{ github.event.pull_request.head.sha }}"

      - name: Publish to pkg.pr.new
        if: ${{ github.event_name == 'workflow_dispatch' || steps.changed_packages.outputs.paths != '' }}
        env:
          API_URL: https://pkg.pr.new
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            pnpm dlx pkg-pr-new@latest publish --pnpm --peerDeps './libs/*'
          else
            pnpm dlx pkg-pr-new@latest publish --pnpm --peerDeps ${{ steps.changed_packages.outputs.paths }}
          fi
        continue-on-error: true
