import { CallbackManagerForToolRun } from "@langchain/core/callbacks/manager";
import { Tool, type ToolParams } from "@langchain/core/tools";
import { Seltz, type SearchOptions } from "seltz";

/**
 * Options for the SeltzSearchResults tool.
 */
export type SeltzSearchResultsFields = ToolParams & {
  client: Seltz;
  searchArgs?: SearchOptions;
};

/**
 * Seltz web knowledge search tool integration.
 *
 * Seltz provides fast, up-to-date web data with context-engineered
 * web content and sources for real-time AI reasoning.
 *
 * Setup:
 * Install `@langchain/seltz` and `seltz`. You'll also need an API key
 * from [Seltz](https://www.seltz.ai/?utm_source=langchainjs&utm_medium=integration&utm_campaign=seltz-package).
 *
 * ```bash
 * npm install @langchain/seltz seltz
 * ```
 *
 * ## [Constructor args](https://api.js.langchain.com/classes/_langchain_seltz.SeltzSearchResults.html#constructor)
 *
 * <details open>
 * <summary><strong>Instantiate</strong></summary>
 *
 * ```typescript
 * import { SeltzSearchResults } from "@langchain/seltz";
 * import { Seltz } from "seltz";
 *
 * const client = new Seltz({ apiKey: process.env.SELTZ_API_KEY });
 *
 * const tool = new SeltzSearchResults({
 *   client,
 *   searchArgs: {
 *     maxDocuments: 5,
 *   },
 * });
 * ```
 * </details>
 *
 * <br />
 *
 * <details>
 *
 * <summary><strong>Invocation</strong></summary>
 *
 * ```typescript
 * await tool.invoke("what is the current weather in sf?");
 * ```
 * </details>
 *
 * <br />
 *
 * <details>
 *
 * <summary><strong>Invocation with tool call</strong></summary>
 *
 * ```typescript
 * // This is usually generated by a model, but we'll create a tool call directly for demo purposes.
 * const modelGeneratedToolCall = {
 *   args: {
 *     input: "what is the current weather in sf?",
 *   },
 *   id: "tool_call_id",
 *   name: tool.name,
 *   type: "tool_call",
 * };
 * await tool.invoke(modelGeneratedToolCall);
 * ```
 *
 * ```text
 * ToolMessage {
 *   "content": "...",
 *   "name": "seltz_search_results_json",
 *   "additional_kwargs": {},
 *   "response_metadata": {},
 *   "tool_call_id": "tool_call_id"
 * }
 * ```
 * </details>
 */
export class SeltzSearchResults extends Tool {
  static lc_name(): string {
    return "SeltzSearchResults";
  }

  description =
    "A wrapper around Seltz Web Knowledge Search. Input should be a search query. Output is a JSON array of the query results with web content and sources.";

  name = "seltz_search_results_json";

  private client: Seltz;

  searchArgs?: SearchOptions;

  constructor(fields: SeltzSearchResultsFields) {
    super(fields);
    this.client = fields.client;
    this.searchArgs = fields.searchArgs;
  }

  protected async _call(
    input: string,
    _runManager?: CallbackManagerForToolRun
  ): Promise<string> {
    const response = await this.client.search(input, this.searchArgs);
    const documents = response.documents.map((doc) => ({
      url: doc.url,
      content: doc.content,
    }));
    return JSON.stringify({ documents });
  }
}
